## Instructions

## Data Analytics at Scale Summative Assessment

You have been contracted as a consultant for Find Images Now (FIN), a tech start-up that wants to match and cluster images at scale. FIN has identified a promising technique but needs help evaluating the performance of the approach. Your evaluation should assess both the accuracy and computational costs (e.g., CPU, memory, runtime demands and how these scale with the number of images as input). 

In particular, FIN has identified “image hashing” approaches and identified the image hash library in Python: https://github.com/JohannesBuchner/imagehash as well as its own in-house hashing approach, called FINd, for which a pure Python implementation is available at https://github.com/oxfordinternetinstitute/das2020 . 
Candidates must first seek to optimize FINd by identifying what portions of the algorithm are computational bottlenecks, implementing alternatives, and comparing computational performance. Candidates must plan and implement two or three optimizations. These optimizations may include: 
* use of scientific Python library such as numpy, scipy, and pandas, 
* different execution approaches (e.g., single process on one CPU vs multiprocessing on a single computer vs distributed approaches), 
* use of GPUs, 
* use of C-compiled code (i.e., cython), 
* etc. 

When implementing the optimizations, candidates should ensure the correctness of their output by writing an appropriate unit test. They should also profile the code to analyse CPU, memory, runtime, and other relevant aspects of computational performance.  

After this, candidates must compare the performance (both in terms of accuracy and computational costs) of two methods from the imagehash library to their optimized version of FINd using the dataset provided in class. That is, compare FINd with any two of the following from the imagehash library: 
* average hashing (aHash) 
* perception hashing (pHash) 
* difference hashing (dHash) 
* wavelet hashing (wHash) 

FIN expect a written report, not to exceed 3,500 words, consisting of two parts. Part 1 will report on FINd including an initial assessment of the performance of the code, the optimizations attempted, and the resulting changes (positive or negative) in computational performance. Candidates should discuss any relevant trade-offs (e.g., CPU vs. memory) of these optimizations. The second half of the report should focus on how FINd compares to the two other image hashing methods selected. This part should analyse both the accuracy of the results as well as the computational costs. The report should focus most in-depth on the trade-offs of different approaches (e.g., the advantages and disadvantages of each approach and how the approaches compare to one another). Finally, candidates should discuss which approach is the 'best' for the given dataset and FIN’s need to match similar images at scale. 

### Further details: 
Projects will be examined based on the following criteria and approximate weights: 
* Part 1 
    * 15 points Clear plan for and analysis of the provided FINd algorithm  
    * 5 points - Executable code analysing the provided FINd algorithm 
    * 10 points - Clear rationale/justification for the planned optimizations for FINd along with a clear description of two or three computational optimizations to FINd that the author will implement and compare (and the relative ‘difficulty’ of these approaches [see below]) 
    * 10 points - Executable code that implements the described optimizations 
    * 15 points - Comparison of each optimization (i.e., what trade-offs are involved) 
* Part 2 
    * 15 points - Comparison of the accuracy and performance of FINd against two other image hashing approaches 
    * 10 points - Executable code that implements the comparisons between FINd and two other image hashing approaches 
    * 20 points - Discussion as to which approach is most suited for the specific data and task. 

The best projects will typically contain at least some of the following: 
* Evidence that the candidate has gone beyond the materials presented in class and the lab sessions 
* Include multiple approaches that are clearly distinct. For example, comparing the performance three different Python libraries is considerably easier than implementing single-process, multi-process, and distributed approaches. 
* Have clear code with sufficient comments/documentation for it to be easily understood  
* Be well-written and demonstrate originality 

### FAQs 
* Can I base my project purely on the code distributed in class? - Yes, but try and at least use it in an original way. A project which simply duplicates a class exercise is unlikely to get a good mark, though it likely would not fail if it was at least well executed 
* Can I use code found on the Internet? Can I use library X? - Yes. Understanding another person’s code / library is a fundamental part of programming, but it is important to understand the code including its computational and memory implications. Following best practices, please cite any sources from where you obtained code and be clear about what modifications you made.  
* Can one of my approaches be a standalone software package (e.g., NodeXL, QDA Minner, etc.) - Not for this class: please choose approaches that require programming 
* Can one of my approaches be in a language other than Python? - No. For the purpose of this assignment, please only compare Python approaches. 
* One of my computational approaches is unlikely to finish in the time available. Help! - It is perfectly fine (and in fact good practice) to profile your code on a subset of the data if the data set is very large. There is no requirement that you run all your approaches on the full dataset. 
* Can I work together with another student? - No. The report submitted and code developed must be entirely your own work. Collaboration with another student in the course is not allowed. 

In [515]:
from FINd import FINDHasher
import FINd_optim
# from FINd_optim import FINDHasher2
import imagehash
from PIL import Image

In [301]:
# Additional import statements
import os
import random
random.seed(42)
import pickle
import numpy as np
import math

In [516]:
findHasher=FINDHasher()
findHasher2 = FINd_optim.FINDHasher2()

AttributeError: module 'FINd_optim' has no attribute 'FINDHasher2'

In [13]:
ex1=findHasher.fromFile("das_images/0040_10318987.jpg")
ex2=findHasher.fromFile("das_images/0040_10321701.jpg")

ex3=findHasher.fromFile("das_images/0120_27768345.jpg")

img=Image.open("das_images/0120_28335973.jpg")
ex4=findHasher.fromImage(img)

In [14]:
%prun findHasher.fromFile("das_images/0040_10318987.jpg")

         500235 function calls in 0.496 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.343    0.343    0.382    0.382 FINd.py:167(boxFilter)
        1    0.032    0.032    0.095    0.095 FINd.py:66(fillFloatLumaFromBufferImage)
    62500    0.024    0.000    0.063    0.000 Image.py:1345(getpixel)
    62504    0.023    0.000    0.031    0.000 Image.py:801(load)
   125000    0.022    0.000    0.022    0.000 {built-in method builtins.max}
   125000    0.018    0.000    0.018    0.000 {built-in method builtins.min}
        1    0.009    0.009    0.009    0.009 FINd.py:110(dct64To16)
    62500    0.009    0.000    0.009    0.000 {method 'getpixel' of 'ImagingCore' objects}
    62503    0.008    0.000    0.008    0.000 {method 'pixel_access' of 'ImagingCore' objects}
        1    0.001    0.001    0.495    0.495 FINd.py:39(fromFile)
        1    0.001    0.001    0.001    0.001 FINd.py:100(decimateFloat)
        1

In [20]:
das_images = list(os.listdir("das_images"))

list

In [31]:
images_sample = random.sample(das_images, 100)

In [45]:
orig_results = []
for image in images_sample:
    orig_results.append(findHasher.fromFile(f"das_images/{image}"))

In [49]:
pickle.dump(orig_results, open('orig_results.p', 'wb'))

### Code Profiling

In [32]:
# Profiling using cProfile
%%prun
for image in images_sample:
    findHasher.fromFile(f"das_images/{image}")

         49346155 function calls in 48.138 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      100   33.524    0.335   37.445    0.374 FINd.py:167(boxFilter)
      100    2.966    0.030    8.958    0.090 FINd.py:66(fillFloatLumaFromBufferImage)
  6165369    2.307    0.000    5.988    0.000 Image.py:1345(getpixel)
 12330738    2.110    0.000    2.110    0.000 {built-in method builtins.max}
  6165769    2.043    0.000    2.796    0.000 Image.py:801(load)
 12330738    1.811    0.000    1.811    0.000 {built-in method builtins.min}
      100    0.929    0.009    0.929    0.009 FINd.py:110(dct64To16)
  6165369    0.886    0.000    0.886    0.000 {method 'getpixel' of 'ImagingCore' objects}
  6165669    0.753    0.000    0.753    0.000 {method 'pixel_access' of 'ImagingCore' objects}
      100    0.250    0.002    0.250    0.002 {built-in method io.open}
      100    0.129    0.001   48.132    0.481 FINd.py:39(fromFile)
      1

We see that the most time is spent on the boxFilter() and fillFloatLumaFromBufferImage() functions, so we will mainly look at these for performance tuning. Now let's use line profiler to dive into these specific functions

In [56]:
path_to_image = "das_images/0040_10318987.jpg"

%lprun -f findHasher.boxFilter findHasher.fromFile(path_to_image)

Timer unit: 1e-06 s

Total time: 2.32521 s
File: /Users/willemzents/Documents/SDS/Code/Michaelmas/DAS/das-summative/FINd.py
Function: boxFilter at line 167

Line #      Hits         Time  Per Hit   % Time  Line Contents
   167                                           	@classmethod
   168                                           	def boxFilter(cls,input,output,rows,cols,rowWin,colWin):
   169         1          2.0      2.0      0.0  		halfColWin = int((colWin + 2) / 2)  # 7->4, 8->5
   170         1          0.0      0.0      0.0  		halfRowWin = int((rowWin + 2) / 2) 
   171       251        129.0      0.5      0.0  		for i in range(0,rows):
   172     62750      19660.0      0.3      0.8  			for j in range(0,cols):
   173     62500      19858.0      0.3      0.9  				s=0
   174     62500      39035.0      0.6      1.7  				xmin=max(0,i-halfRowWin)
   175     62500      31982.0      0.5      1.4  				xmax=min(rows,i+halfRowWin)
   176     62500      30790.0      0.5      1.3  				ymi

In [57]:
path_to_image = "das_images/0040_10318987.jpg"

%lprun -f findHasher.fillFloatLumaFromBufferImage findHasher.fromFile(path_to_image)

Timer unit: 1e-06 s

Total time: 0.192876 s
File: /Users/willemzents/Documents/SDS/Code/Michaelmas/DAS/das-summative/FINd.py
Function: fillFloatLumaFromBufferImage at line 66

Line #      Hits         Time  Per Hit   % Time  Line Contents
    66                                           	def fillFloatLumaFromBufferImage(self, img, luma):
    67         1          3.0      3.0      0.0  		numCols, numRows = img.size
    68         1         59.0     59.0      0.0  		rgb_image = img.convert("RGB")
    69         1          2.0      2.0      0.0  		numCols, numRows = img.size
    70       251         78.0      0.3      0.0  		for i in range(numRows):
    71     62750      19524.0      0.3     10.1  			for j in range(numCols):
    72     62500     131487.0      2.1     68.2  				r, g, b = rgb_image.getpixel((j, i))
    73                                           				luma[i * numCols + j] = (
    74                                           					self.LUMA_FROM_R_COEFF * r
    75           

### Scraps

In [483]:
from matrix import MatrixUtil
from PIL import Image

img=Image.open("das_images/0120_28335973.jpg")

img = img.copy()
img.thumbnail((512, 512))

LUMA_FROM_R_COEFF = float(0.299)
LUMA_FROM_G_COEFF = float(0.587)
LUMA_FROM_B_COEFF = float(0.114)

numCols, numRows = img.size
buffer1 = MatrixUtil.allocateMatrixAsRowMajorArray(numRows, numCols)
buffer2 = MatrixUtil.allocateMatrixAsRowMajorArray(numRows, numCols)

buffer1_np = np.array(MatrixUtil.allocateMatrixAsRowMajorArray(numRows, numCols))
buffer2_np = np.array(MatrixUtil.allocateMatrixAsRowMajorArray(numRows, numCols))

buffer64x64 = MatrixUtil.allocateMatrix(64, 64)
buffer16x64 = MatrixUtil.allocateMatrix(16, 64)
buffer16x16 = MatrixUtil.allocateMatrix(16, 16)
numCols, numRows = img.size

def computeBoxFilterWindowSize(dimension):
    """ Round up."""
    return int(
        (dimension + 64 - 1)
        / 64
    )

windowSizeAlongRows = computeBoxFilterWindowSize(numCols)
windowSizeAlongCols = computeBoxFilterWindowSize(numRows)

def fillFloatLumaFromBufferImage(img, luma):
    rgb_image = img.convert("RGB")
    numCols, numRows = img.size
    for i in range(numRows):
        for j in range(numCols):
            r, g, b = rgb_image.getpixel((j, i))
            luma[i * numCols + j] = (
                LUMA_FROM_R_COEFF * r
                + LUMA_FROM_G_COEFF * g
                + LUMA_FROM_B_COEFF * b
            )

fillFloatLumaFromBufferImage(img, buffer1)


def boxFilter(input, output, rows, cols, rowWin, colWin):
    halfColWin = int((colWin + 2) / 2)  # 7->4, 8->5
    halfRowWin = int((rowWin + 2) / 2)
    for i in range(0, rows):
        for j in range(0, cols):
            s = 0
            xmin = max(0, i-halfRowWin)
            xmax = min(rows, i+halfRowWin)
            ymin = max(0, j-halfColWin)
            ymax = min(cols, j+halfColWin)
            for k in range(xmin, xmax):
                for l in range(ymin, ymax):
                    s += input[k*rows+l]
            output[i*rows+j] = s/((xmax-xmin)*(ymax-ymin))
    
    return output

def boxFilterNumpy(input, output, rows, cols, rowWin, colWin):
    halfColWin = int((colWin + 2) / 2)  # 7->4, 8->5
    halfRowWin = int((rowWin + 2) / 2)
    
    output = np.array(output)
    input = np.array(input)

    for i in range(0, rows):
        for j in range(0, cols):
            
            x = np.array(np.arange(max(0, i-halfRowWin), min(rows, i+halfRowWin)))
            y = np.array(np.arange(max(0, j-halfColWin), min(cols, j+halfColWin)))

            arr = np.array((np.ones((y.size,x.size)) * x * numRows + y.reshape(-1,1)), dtype=int)
            output[i*rows+j] = np.mean(input[arr.flatten()])

    return output

In [480]:
boxFilterNumpy(buffer1, buffer2, numRows, numCols, windowSizeAlongRows, windowSizeAlongCols)


array([190.04877778, 200.0175    , 205.76706667, ..., 127.403625  ,
       123.9092    , 124.0609375 ])

In [400]:
halfColWin = int((windowSizeAlongCols + 2) / 2)  # 7->4, 8->5
halfRowWin = int((windowSizeAlongRows + 2) / 2)

xmin = np.array([max(0, i-halfRowWin) for i in range(0, 250)])
xmax = np.array([min(250, i+halfRowWin) for i in range(0, 250)])
ymin = np.array([max(0, j-halfColWin) for j in range(0, 250)])
ymax = np.array([min(250, j+halfColWin) for j in range(0, 250)])

x = np.array(range(xmin[3], xmax[3]))
y = np.array(range(ymin[3], ymax[3]))

In [513]:
xmin = 10
xmax = 14
ymin = 10
ymax = 16

x = np.array(np.arange(xmin, xmax))
y = np.array(np.arange(ymin, ymax))

# np.array(np.ones((ymax-ymin, xmax-xmin)) * x * numRows + y.reshape(-1,1)).astype(int)
# np.ones((xmax-xmin, ymax-ymin)) * x * numRows + y.reshape(-1,1)
# np.ones((xmax-xmin, ymax-ymin)) * x * numRows
# np.ones((ymax-ymin,xmax-xmin)) * x
# np.ones_like(x*y) #* np.ones_like(y)

len(np.concatenate((x,y)))#.reshape(x.size,y.size)

10

In [362]:
s=0
for k in range(xmin, xmax):
    for l in range(ymin, ymax):
        s += buffer1[k*numRows+l]
print(s)



6585.267


In [436]:
func = np.vectorize(lambda x: buffer1[x])


a = np.matrix([x,]*len(y))
b = np.matrix([y,]*len(x)).transpose()
prod = np.prod(a.shape)
# out = np.sum(a * 256 + b) / np.prod(a.shape)
out = a * 256 + b
out.A1

array([ 256,  512,  768, 1024, 1280, 1536,  257,  513,  769, 1025, 1281,
       1537,  258,  514,  770, 1026, 1282, 1538,  259,  515,  771, 1027,
       1283, 1539,  260,  516,  772, 1028, 1284, 1540,  261,  517,  773,
       1029, 1285, 1541])

In [488]:
x = np.array(range(0,3))
x.reshape(-1,1)

array([[0],
       [1],
       [2]])

In [287]:
np.array([y,]*len(x))

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [460]:
outputnumpy = boxFilterNumpy(buffer1, buffer2, numRows, numCols, windowSizeAlongRows, windowSizeAlongCols)
output = boxFilter(buffer1, buffer2, numRows, numCols, windowSizeAlongRows, windowSizeAlongCols)
assert outputnumpy[0] == np.array(output)[0]

AssertionError: 

In [464]:
outputnumpy[0]

190.04877777777776

In [478]:
x = np.array(range(10, 16))
y = np.array(range(10, 16))
z = np.matrix(([1,2],[3,4]), dtype=int)
z

matrix([[1, 2],
        [3, 4]])

In [468]:
%prun boxFilter(buffer1, buffer2, numRows, numCols, windowSizeAlongRows, windowSizeAlongCols)

         250004 function calls in 0.388 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.347    0.347    0.388    0.388 <ipython-input-448-3fc76dc02a9a>:50(boxFilter)
   125000    0.022    0.000    0.022    0.000 {built-in method builtins.max}
   125000    0.018    0.000    0.018    0.000 {built-in method builtins.min}
        1    0.000    0.000    0.388    0.388 {built-in method builtins.exec}
        1    0.000    0.000    0.388    0.388 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

In [484]:
%prun boxFilterNumpy(buffer1, buffer2, numRows, numCols, windowSizeAlongRows, windowSizeAlongCols)

         1875006 function calls in 1.903 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.675    0.675    1.902    1.902 <ipython-input-483-e43c4a435ba7>:67(boxFilterNumpy)
    62500    0.191    0.000    0.505    0.000 _methods.py:134(_mean)
    62500    0.145    0.000    0.145    0.000 {method 'reduce' of 'numpy.ufunc' objects}
   250002    0.138    0.000    0.138    0.000 {built-in method numpy.array}
   125000    0.119    0.000    0.701    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
   125000    0.095    0.000    0.095    0.000 {built-in method numpy.arange}
    62500    0.083    0.000    0.093    0.000 _methods.py:50(_count_reduce_items)
    62500    0.078    0.000    0.583    0.000 fromnumeric.py:3231(mean)
    62500    0.054    0.000    0.054    0.000 {method 'flatten' of 'numpy.ndarray' objects}
    62500    0.048    0.000    0.212    0.000 numeric.py:159(ones)
    6250

In [485]:
%lprun -f boxFilterNumpy boxFilterNumpy(buffer1, buffer2, numRows, numCols, windowSizeAlongRows, windowSizeAlongCols)

Timer unit: 1e-06 s

Total time: 2.17112 s
File: <ipython-input-483-e43c4a435ba7>
Function: boxFilterNumpy at line 67

Line #      Hits         Time  Per Hit   % Time  Line Contents
    67                                           def boxFilterNumpy(input, output, rows, cols, rowWin, colWin):
    68         1          8.0      8.0      0.0      halfColWin = int((colWin + 2) / 2)  # 7->4, 8->5
    69         1          1.0      1.0      0.0      halfRowWin = int((rowWin + 2) / 2)
    70                                               
    71         1       2714.0   2714.0      0.1      output = np.array(output)
    72         1       3814.0   3814.0      0.2      input = np.array(input)
    73                                           
    74       251        132.0      0.5      0.0      for i in range(0, rows):
    75     62750      33372.0      0.5      1.5          for j in range(0, cols):
    76                                           
    77                                        

In [470]:
%lprun -f boxFilter boxFilter(buffer1, buffer2, numRows, numCols, windowSizeAlongRows, windowSizeAlongCols)

Timer unit: 1e-06 s

Total time: 2.3126 s
File: <ipython-input-448-3fc76dc02a9a>
Function: boxFilter at line 50

Line #      Hits         Time  Per Hit   % Time  Line Contents
    50                                           def boxFilter(input, output, rows, cols, rowWin, colWin):
    51         1         13.0     13.0      0.0      halfColWin = int((colWin + 2) / 2)  # 7->4, 8->5
    52         1          2.0      2.0      0.0      halfRowWin = int((rowWin + 2) / 2)
    53       251         77.0      0.3      0.0      for i in range(0, rows):
    54     62750      19791.0      0.3      0.9          for j in range(0, cols):
    55     62500      19598.0      0.3      0.8              s = 0
    56     62500      36247.0      0.6      1.6              xmin = max(0, i-halfRowWin)
    57     62500      31248.0      0.5      1.4              xmax = min(rows, i+halfRowWin)
    58     62500      30513.0      0.5      1.3              ymin = max(0, j-halfColWin)
    59     62500      30501.0 

## Submission Instructions

Please produce: a 3500 word report in PDF format along with all code and its output. The code must be provided in an executable format (e.g., .py Python scripts or .ipynb Jupyter notebooks). The work must be submitted electronically via the Assignment Submission WebLearn Site before midday on Friday of Week 0 (15th January) of Hilary term.

If anything goes wrong with your submission, email msc@oii.ox.ac.uk immediately. In cases where a technical fault that is later determined to be a fault of the WebLearn system (and not a fault of your computer) prevents your submitting the assessment on time, having a time stamped email message will help the Proctors determine if your assessment will be accepted. Please note that you should not wait until the last minute to submit materials since WebLearn can run slowly at peak submission times and this is not considered a technical fault.

Full instructions on using WebLearn for electronic submissions can be found on Canvas.

Candidate Number and Cover Sheet: Remember to use the OII coversheet, stating clearly your candidate number, your course, assignment, title and word count. Your work should be identified ONLY by your candidate number (which can be found by visiting the online Student Self-Service facility).

Remember we are required under regulations to accept your FIRST submission so please make sure you are uploading the correct file.

In [486]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([[1,2,2], [3,7,3]])
x[y.flatten()]

array([2, 3, 3, 4, 8, 4])